### ISSUE TITLE
plugins failed to load

### ISSUE THREAD

**Issue by ariefMudahMy** [KongZ/graylog-plugin-slack-notification#19]
Hi,
im seeing an issue when installing this plugin
`126454:2021-01-11T16:41:20.682+08:00 ERROR [CmdLineTool] Plugin "Slack Notification Plugin" requires version 4.0.1 - not loading!`

my details are : 
- graylog version = Graylog 3.2.6+e255fc
- OS : CentOS 7.8.2003

**Comment by KongZ** [comment]
The plugin version 4.x requires Graylog version 4.x
If you are using Graylog 3.x you need to use plugin version 3.x 

Here is version 3.3.4 https://github.com/KongZ/graylog-plugin-slack-notification/releases/tag/v3.3.4
