### ISSUE TITLE
Sender Name not working using bot token

### ISSUE THREAD

**Issue by niorg** [KongZ/graylog-plugin-slack-notification#30]
I have configured a slack notification using a bot token (xoxb-), a custom Sender Name and a custom Message Icon. The slack message gets delivered correctly, but the Sender Name is still the app name not the one specified in the notification settings. The icon however is updated as expected. No errors are logged in graylog.  

The `chat:write.customize` OAuth scope is enabled. Using the slack API I'm able to override the username, it's just not working via this plugin.

**Comment by KongZ** [comment]
The Slack API permission changes over time. 
Now, you will require `chat:write.customize` permission in order to set the sender name. When creating app, make sure to have the permission.

Sees https://api.slack.com/scopes/chat:write.customize

**Comment by niorg** [comment]
As I wrote in my issue, that permission is enabled.

**Comment by KongZ** [comment]
Sorry, I miss reading. Since the bot's username is legacy API. It might have changed. I will take a look.

**Comment by KongZ** [comment]
Fixed and release with [4.3.10](https://github.com/KongZ/graylog-plugin-slack-notification/releases/tag/v4.3.10)
