### ISSUE TITLE
Compile for graylog 5.1.1

### ISSUE THREAD

**Issue by scholdan** [KongZ/graylog-plugin-slack-notification#34]
Hello, 

Would you please bump the release?

**Comment by KongZ** [comment]
I will. It need to recompile with specific version.

**Comment by scholdan** [comment]
Thanks :)

**Comment by scholdan** [comment]
In what timeframe do you think it will be ready?

**Comment by KongZ** [comment]
https://github.com/KongZ/graylog-plugin-slack-notification/releases/tag/v5.1.2
